# when ´period_method: date': use start/end dates to select data
# when ´period_method: n_end_shifts´: use n_end_shifts to select n last shifts
run_start_date: ${run_start_date}
run_end_date: ${run_end_date}
run_period_method: ${run_period_method}  # 'date' or 'n_end_shifts'
run_n_end_shifts: ${run_n_end_shifts}
